name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Houssse
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Moscow
          plugin_languages: yes
          # plugin_languages_fresh: yes 
          # plugin_languages_ignored: ะก
          # plugin_languages_limit: 5
          # plugin_achievements: yes
          # plugin_achievements_display: compact
          # plugin_achievements_threshold: ""
          # plugin_achievements_secrets: yes
          plugin_notable: yes
          # plugin_notable_filter: stars:10
          
